# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=1000)),
                ('album_genre', models.CharField(choices=[(b'T', b'Turku'), (b'TS', b'TurkSanatMuzigi'), (b'A', b'Arabesk'), (b'P', b'Pop')], max_length=200)),
                ('song1', models.CharField(max_length=100)),
                ('singer_name', models.CharField(max_length=50)),
                ('song2', models.CharField(max_length=100)),
                ('song3', models.CharField(max_length=100)),
                ('album_logo', models.ImageField(blank=True, upload_to=b'music_imgs')),
                ('topic_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
