# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_foto', models.ImageField(blank=True, upload_to=b'music_imgs')),
                ('singer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=1000)),
                ('video', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='singer_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='song1',
        ),
        migrations.RemoveField(
            model_name='album',
            name='song2',
        ),
        migrations.RemoveField(
            model_name='album',
            name='song3',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Singer'),
            preserve_default=False,
        ),
    ]
