# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20171211_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
