# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_remove_album_album_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_date',
            field=models.CharField(default=1, max_length=1233),
            preserve_default=False,
        ),
    ]
