# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_album_album_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 8, 53, 29, 854796)),
        ),
    ]
