# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20171211_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 9, 24, 9, 537841)),
        ),
        migrations.AddField(
            model_name='song',
            name='song_point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 9, 24, 9, 311189)),
        ),
    ]
