# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20171211_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_lyrics',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 11, 46, 5, 832811)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 11, 46, 5, 844434)),
        ),
    ]
