# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20171211_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 11, 50, 48, 431941)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 11, 50, 48, 545027)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_lyrics',
            field=models.CharField(max_length=10000),
        ),
    ]
