# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20171211_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 11, 54, 43, 563397)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 11, 54, 43, 921818)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
