# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 12:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20171211_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 12, 3, 13, 920074)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 12, 3, 14, 32845)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_lyrics',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
