# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20171211_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='singer_life',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 17, 53, 30, 401428)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 11, 17, 53, 30, 544885)),
        ),
    ]
