# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20171220_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roportaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 20, 19, 56, 13, 243569)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 20, 19, 56, 13, 244980)),
        ),
    ]
