# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_auto_20171220_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='roportaj',
            name='textuzun',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 20, 20, 10, 54, 555426)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 20, 20, 10, 54, 556904)),
        ),
    ]
