# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20171220_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 20, 21, 27, 8, 6314)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 20, 21, 27, 8, 7597)),
        ),
    ]
